### ISSUE TITLE
Memory usage of this app

### ISSUE THREAD

**Issue by MP-ICT-Diensten** [AdyRock/com.community.store#3]
After creating my Grafana dashboard I notice that the community checker op my Homey Pro uses more memory than I would expect. Is it possible to reduce memory usage, because now it's an app worth to be switched off ;) 

The below graph is an average over 7 days where this app is average 24 Mb in size an on the top of the list of a total of 36 apps.

![2020-08-17_19-28-19](https://user-images.githubusercontent.com/28575285/90426933-21965900-e0c2-11ea-89ca-21992bcc2cdb.png)

**Comment by AdyRock** [comment]
I don't see any way to reduce the memory usage. The bulk of the app itself is the athom-api used to fetch the app information.
The memory usage during use is very small most of the time, it's just when it fetches all the app information there will be a spike but it discards the data once it has extracted what it needs. Generally it only takes a few seconds to process and it does that once per day.

**Comment by MP-ICT-Diensten** [comment]
May be clean the collected list after processing?  
Below the graph of the same 7 days, on the end (today) I installed the 0.0.7 version, a fresh app start.

![2020-08-17_20-54-50](https://user-images.githubusercontent.com/28575285/90433412-121c0d80-e0cc-11ea-8f57-b97ef0f80cf9.png)

**Comment by AdyRock** [comment]
I have checked in the debugger and there was one cache of data fro the community store that wasn't be cleared. Version 0.0.8 clears that straight after processing it so saves about 2 - 3k.
Apart from that it is not retaining anything that is not required. The list of apps and version numbers it maintains to show in the list is very small as it just has the app name, app version number and detected version number. So that is like ~50 to 200 bytes per app that has an update.
Unfortunately I need to use the athom-api to get the list of apps and just by including the api the app consumes around 12k more.

**Comment by MP-ICT-Diensten** [comment]
Its a bit better now indeed.

I realized that this app does not need to run 24h per day, so I made a flow to enable the app at 20:02 and disable the app again after 10 minutes. In between the app execute the check at 20:05 for new apps and notify me.
